config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'secure'
 
  get '/home', to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  get '/stats', to: 'pages#stats'

resources :entries do
  resources :questions do
    post :add_answer, on: :collection
  end
end
  
  # root "pages#home"
  root 'entries#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  has_many :questions, dependent: :destroy

  validates :description, presence: { message: "can't be blank. Please describe the quiz." }
  validate :description_should_be_valid
  validates :name, presence: { message: "can't be blank. Please provide a name for the quiz." }

  # encrypts :name, deterministic: true

  private

  def description_should_be_valid
    if description.present? && description.length < 10
      errors.add(:description, "is too short. Please provide more details.")
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :entry
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers


  validates :text, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :entries, dependent: :destroy
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_entry
  before_action :set_question
  before_action :set_answer, only: %i[edit update destroy]

  def new
    @answer = @question.answers.new
  end

  def create
    @answer = @question.answers.new(answer_params)
    if @answer.save
      flash.now[:notice] = "Answer created successfully."
      respond_to do |format|
        format.html { redirect_to entry_question_path(@entry, @question) }
        format.turbo_stream {}
      end
    else
      flash.now[:alert] = "Failed to create answer."
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @answer.update(answer_params)
      flash.now[:notice] = "Answer updated successfully."
      respond_to do |format|
        format.html { redirect_to entry_question_path(@entry, @question) }
        format.turbo_stream
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @answer.destroy
    flash.now[:notice] = "Answer deleted successfully."
    respond_to do |format|
      format.html { redirect_to entry_question_path(@entry, @question) }
      format.turbo_stream
    end
  end

  private

  def set_entry
    @entry = current_user.entries.find(params[:entry_id])
  end

  def set_question
    @question = @entry.questions.find(params[:question_id])
  end

  def set_answer
    @answer = @question.answers.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:answer_text, :correct) 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_entry, only: %i[show edit update destroy]

    def index
      @entries = current_user.entries
      @main_entry = current_user.entries.first
    end

    def show
    end

  def new 
    @entry = Entry.new
  end

  def create 
    @entry = current_user.entries.new(entry_params)
    if @entry.save
      flash.now[:notice] = "Quiz <strong>#{@entry.name}</strong> - created successfully.".html_safe
      respond_to do |format|
        format.html { redirect_to root_path }
        format.turbo_stream {}
      end
    else
      # flash:now[:alert] = "Quiz creation failed.".html_safe
      render :new, status: :unprocessable_entity
    end
  end

  def edit 
  
  end

  def update
     if @entry.update(entry_params)
      flash.now[:notice] = "Quiz <strong>#{@entry.name}</strong> - updated successfully.".html_safe
        respond_to do |format|
        format.html { redirect_to @entry }
        format.turbo_stream {}
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end
  

  def destroy
    @entry.destroy
    flash.now[:notice] = "Quiz <strong>#{@entry.name}</strong> - deleted successfully.".html_safe
    respond_to do |format|
      format.html { redirect_to root_path }
      format.turbo_stream {}
    end
  end

  private

  def entry_params
    params.require(:entry).permit(:name, :description)
  end

  def set_entry
    @entry = current_user.entries.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

    def about
    end

    def contact
    end

    def stats
    
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_entry, except: []
  before_action :set_question, only: %i[show edit update destroy]

  def index
    @questions = @entry.questions
    @question = @entry.questions.new
    @question.answers.build
  end

  def show
  respond_to do |format|
    format.html
  end
end


  def new
    @entry = current_user.entries.find(params[:entry_id]) # or use before_action :set_entry
    @question = @entry.questions.new
    @question.answers.build
  end

def create
  @question = @entry.questions.new(question_params)

  if params[:commit] == "Add answer"
    @question.answers.build

    render :index
    return
  end

  if @question.save
      if params[:question][:answer_text].present?
      @question.answers.create(answer_text: params[:question][:answer_text])
    end
    flash.now[:notice] = "Question created successfully."
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Question created successfully." }
      format.turbo_stream do
        # render turbo_stream: [
        #   turbo_stream.update("flash", partial: "shared/flash"),
        # ]
        redirect_to root_path, status: :see_other
      end
    end
else
    flash.now[:alert] = "Failed to create question."
    respond_to do |format|
      format.html { render :new, status: :unprocessable_entity }
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update("flash", partial: "shared/flash"),
        ]
      end
    end
  end
end



  def edit
  end

  def update
    if @question.update!(question_params)
      flash.now[:notice] = "Question updated successfully.".html_safe
      respond_to do |format|
        format.html { redirect_to entry_question_path(@entry, @question) }
        format.turbo_stream
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @question.destroy
    flash.now[:notice] = "Question deleted successfully.".html_safe
    respond_to do |format|
      format.html { redirect_to entry_questions_path(@entry) }
      format.turbo_stream
    end
  end

  # def add_answer
  #   @questions = @entry.questions
  #   @question = @entry.questions.new
  #   @question.answers.build

  #   render :index
  # end

  private

def set_entry
  @entry = current_user.entries.find(params[:entry_id])
end

def set_question
  @question = @entry.questions.find(params[:id])
end

def question_params
  params.require(:question).permit(:text, :description, answers_attributes: [:id, :answer_text, :_destroy])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def logo(size = 'h2')
    link_to(root_path, class: "logo #{size}") do
      "<i class=\'bi bi-alipay\'></i> JKZQUIZ".html_safe
    end
  end

  def account_page?
    current_page?(edit_user_registration_path)
  end

  def format_time(time)
    time.strftime("%m/%d/%Y %I:%M %p")
  end

  def render_flash_stream
    turbo_stream.update("flash", partial: "shared/flash", locals: { flash: flash })
  end
end

app/helpers/flash_helper.rb
module FlashHelper
    def flash_class(type)
      case type
      when 'notice' then "success"
      when 'alert'  then "danger"
      end
    end
end

app/views/entries/_entry.html.erb
<%= link_to(entry_path(entry),
 class: 'nav-link',
    data: { turbo_frame: 'main_dashboard'},
    id: dom_id(entry)) do %>
   <%= render(layout: 'entries/entry_name', locals: {entry: entry}) do %>
      <%= entry.name %>
    <% end %>
<% end %>

app/views/entries/_entry_name.html.erb
<div class="d-flex align-items-center">
    <div class="entry-favicon bg-info text-white rounded-circle d-flex justify-content-center align-items-center" style="width: 42px; height: 42px;">
        <i class="bi bi-anthropic"></i>
    </div>
    <%= yield %>
</div>

app/views/entries/_entry_quiz.html.erb
<div class="container">
  <div class="quiz__container" id="quiz">
    <div class="quiz__header">
      <h2 id="quiz-title">Test Questions</h2>
      <div class="quiz__progress">
        <div class="progress-bar" role="progressbar" style="width: 0%;" aria-valuenow="0" aria-valuemin="0"
          aria-valuemax="100"></div>
      </div>
    </div>
    <div id="question-container">
      <p class="quiz__question" id="question">What is the capital of France?</p>
      <div class="quiz__options" id="options"></div>
    </div>
    <div class="quiz__footer">
      <button class="btn btn-primary" id="next-btn" style="display:none;">Next</button>
      <button class="btn btn-success" id="start-quiz-btn" style="display:none;">Start Real Quiz</button>
      <div class="quiz__timer" id="timer" style="display:none;">Time: 30s</div>
    </div>
  </div>
</div>

app/views/entries/_main.html.erb
<div class="container"
<div class="d-flex flex-column justify-content-between h-100">
  <div>
    <%= render(layout: 'entries/entry_name', locals: { entry: entry }) do %>
      <div class="d-flex align-items-center justify-content-between flex-grow-1">
       <%= turbo_frame_tag :entry_name, class: 'w-100' do %>
      <h1 class="mb-0"><strong><%= entry.name %></strong></h1>
    <% end %>
          <div class="dropdown">
          <button class="btn btn-outline-light border-0 text-dark me-3" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-three-dots-vertical"></i>
          </button>
          <ul class="dropdown-menu">
              <li>
              <%= link_to(edit_entry_path(entry, input: :entry_name), data: {turbo_frame: :entry_name}, class: 'dropdown-item') do %>
                <i class="bi bi-pencil-square"></i> Edit Quiz
              <% end %>
            </li>
            <li>
              <%= link_to(entry_path(entry),
               data: {turbo_method: :delete},
               class: 'dropdown-item text-danger') do %>
                <i class="bi bi-trash3-fill"></i> Delete Quiz
              <% end %>
            </li>
            <li>
          <%= link_to(entry_questions_path(entry),
                      class: 'dropdown-item text-info') do %>
            <i class="bi bi-plus-circle-fill"></i> Add Q/A
          <% end %>
        </li>
          </ul>
        </div>
      </div>
    <% end %>

  <div class="mt-5">
            <ul class="list-group">
            <li class="list-group-item">
        <%= turbo_frame_tag(:entry_name) do %>
          <div class="d-flex justify-content-between align-items-center">
            <div class="form-floating d-flex">
              <%= text_field_tag(:name, entry.name,
                readonly: true,
                class: 'form-control-plaintext',
                placeholder: 'Name') %>
              <%= label_tag(:name, "Name", class: 'fw-bold text-dark') %>
            </div>
            <div class="actions">
              <%= link_to(edit_entry_path(entry, input: :entry_name), class: 'btn btn-outline-light border-0 text-dark') do %>
                <i class="bi bi-pencil-square"></i>
              <% end %>
            </div>
          </div>
        <% end %>
      </li>
            <li class="list-group-item">
          <div class="d-flex justify-content-between align-items-center">
            <div class="form-floating d-flex">
              <%= text_field_tag(:description, entry.description,
                readonly: true,
                class: 'form-control-plaintext',
                placeholder: 'Description') %>
              <%= label_tag(:description, "Description", class: 'fw-bold text-dark') %>
            </div>
            <div class="actions">
              <%= link_to(edit_entry_path(entry, input: :entry_name), class: 'btn btn-outline-light border-0 text-dark') do %>
              <% end %>
            </div>
          </div>
        </li>
        <div class="list-group">
        <div class="flex-grow-1 mt-4 ms-4 mb-4 ps-1">
        <div class="fw-bold">
          <%= link_to(entry, target: :_blank, rel: 'noopener noreferrer') do %>
            <%= entry.name %> <i class="bi bi-box-arrow-up-right ms-1"></i>
          <% end %>
        </div>
      </div>
    </div>
    </div>
  </div>
<div>
  <% if entry.questions.any? %>
  <ul class="list-group mt-3 shadow-sm rounded-3">
    <% entry.questions.each do |question| %>
      <li class="list-group-item py-3">
        <div class="d-flex align-items-start">
          <span class="flex-grow-1"><strong><%= question.text %></strong></span>
        </div>

        <% if question.answers.any? %>
          <ul class="list-group list-group-flush mt-2 ms-3">
            <% question.answers.each do |answer| %>
              <li class="list-group-item d-flex align-items-start border-0 border-top py-2">
                <span class="flex-grow-1"><%= answer.answer_text %></span>
              </li>
            <% end %>
          </ul>
        <% else %>
          <p class="text-muted mt-2 mb-0 small"><em>No answers yet</em></p>
        <% end %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p class="alert alert-info mt-3 mb-0"><strong>No questions available</strong></p>
<% end %>
</div>




  <!-- Footer dates at bottom -->
  <div class="text-center mt-3">
  <small>
    <div>Modified at: <%= format_time(entry.updated_at.in_time_zone("Europe/Riga")) %></div>
    <div>Created at: <%= format_time(entry.created_at.in_time_zone("Europe/Riga")) %></div>
    </small>
  </div>
</div>
</div>

app/views/entries/create.turbo_stream.erb
<%= render_flash_stream %>
<%= turbo_stream.append('entries-list', @entry) %>
<%= turbo_stream.update('main_dashboard') do %>
    <%= render(partial: 'entries/main', locals: { entry: @entry }) %>
    <%= render partial: 'questions/questions_add_button', locals: { main_entry: @entry } %>
<%end %>

app/views/entries/destroy.turbo_stream.erb
<%= render_flash_stream %>
<%= turbo_stream.remove(@entry) %>
<%= turbo_stream.update('main_dashboard') do %>
    <% if current_user.entries.any? %>
    <%= render(partial: 'entries/main', locals: { entry: current_user.entries.first }) %>
    <% else %>
    <%= render(html: content_tag(:h1, "No Quizzes Created.",
     class: "h-100 d-flex align-items-center justify-content-center")) %>
    <% end %>
<% end %>

app/views/entries/edit.html.erb
<%= turbo_frame_tag params[:input] do %>
  <%= form_with model: @entry, class: 'd-flex align-items-center gap-2 w-100', style: 'max-width: 600px;' do |form| %>
    <div class="form-floating flex-grow-1" style="min-width: 0;">
      <%# In Bootstrap 5, floating labels work best with an empty placeholder %>
      <%= form.text_field :name, placeholder: ' ', class: 'form-control' %>
      <%= form.label :name, 'Quiz Name' %>
    </div>

    <div class="btn-group ms-1 flex-shrink-0" role="group">
      <%= form.button type: 'submit', class: 'btn btn-sm btn-outline-success' do %>
        <i class="bi bi-check"></i>
      <% end %>

      <%= link_to entry_path(@entry), class: 'btn btn-sm btn-outline-danger', data: { turbo: false } do %>
        <i class="bi bi-x"></i>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/entries/index.html.erb
<div class="row">
  <div class="entries-actions card d-flex justify-content-end">
    <%= link_to "+ Add New Quiz", new_entry_path,
         class: "btn btn-outline-primary mr-2",
          style: "margin-right: 1rem;",
         data: { turbo_frame: "main_dashboard" } %>

    
  </div>


  <div id="dashboard" class="card shadow-sm">
    <div class="entries-card">
      <div class="entries-card__sidebar">
        <nav id="entries-list" class="nav flex-column">
          <% if @entries.any? %>
            <%= render(@entries) %>
          <% end %>
        </nav>
      </div>
      <div class="entries-card__main" style="overflow-y: scroll;">
        <%= turbo_frame_tag 'main_dashboard' do %>
          <% if @entries.any? %>
            <%= render partial: 'entries/main', locals: { entry: @main_entry } %>
          <% else %>
          
            <%= content_tag :p, "No Quizzes Created.",
                 class: "h-100 d-flex align-items-center justify-content-center" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/entries/new.html.erb
<%= turbo_frame_tag('main_dashboard') do %>
  <div class="d-flex align-items-center justify-content-between">
    <h1>Create New Quiz</h1>
    <%= link_to("Cancel", entries_path, class: "btn btn-sm btn-outline-danger") %>
  </div>

<div class="row mt-4">
  <div class="col-md-12">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <% if @entry.errors.any? %>
            <div id="error_explanation" class="alert alert-danger" role="alert">
              <h4>Please fix the following errors: <%= pluralize(@entry.errors.count, "error") %> found</h4>
              <ul>
                <% @entry.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <%= form_with(model: @entry) do |form| %>
            <div class="form-floating mb-3">
              <%= form.text_field(:name, placeholder: 'Quiz Name', class: 'form-control') %>
              <%= form.label(:name, "Quiz Name") %>
            </div>

            <div class="form-floating mb-3">
              <%= form.text_area :description, 
                    placeholder: "Quiz Description", 
                    class: "form-control", 
                    id: "description_field", 
                    style: "height: 120px" %>
              <%= form.label :description, "Quiz Description", for: "description_field" %>
              <div id="description_counter" class="text-end small text-muted">0 characters</div>
            </div>

            <%= form.submit "+ Create New Quiz", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<% end %>

<script>
  document.addEventListener('DOMContentLoaded', () => {
    const descriptionInput = document.getElementById('description_field');
    const counter = document.getElementById('description_counter');

    function updateCounter() {
      const length = descriptionInput.value.length;
      counter.textContent = `${length} character${length !== 1 ? 's' : ''}`;
    }

    descriptionInput.addEventListener('input', updateCounter);

    // Initialize counter on page load
    updateCounter();

    // Toggle questions fields
    const toggleBtn = document.getElementById('toggle_questions');
    const questionsContainer = document.getElementById('questions_container');

    toggleBtn.addEventListener('click', () => {
      if (questionsContainer.style.display === 'none') {
        questionsContainer.style.display = 'block';
        toggleBtn.textContent = 'Hide Questions';
      } else {
        questionsContainer.style.display = 'none';
        toggleBtn.textContent = 'Add Questions';
        // Optionally clear question inputs when hiding
        questionsContainer.querySelectorAll('input').forEach(input => input.value = '');
      }
    });
  });
</script>

app/views/entries/update.turbo.stream.erb
<%= render_flash_stream %>
<%= turbo_stream.replace(@entry) %>
<%= turbo_stream.update('main_dashboard') do %>
    <%= render(partial: 'entries/main', locals: { entry: @entry }) %>
<%end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "JKZQUIZ App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
  <%= render(partial: 'shared/navbar') %>
  <div id="flash">
        <%= render(partial: 'shared/flash') %>
  </div>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Page</h1>

app/views/pages/contact.html.erb
<div class="mx-auto w-50 p-3">
  <%= form_with url: contact_path, method: :post, local: true, class: "needs-validation" do |f| %>
    <div class="mb-3">
      <%= f.label :name, "Your Name", class: "form-label" %>
      <%= f.text_field :name, class: "form-control", required: true, placeholder: "Enter your full name" %>
      <div class="invalid-feedback">
        Please enter your name.
      </div>
    </div>

    <div class="mb-3">
      <%= f.label :email, "Your Email", class: "form-label" %>
      <%= f.email_field :email, class: "form-control", required: true, placeholder: "Enter your email" %>
      <div class="invalid-feedback">
        Please enter a valid email.
      </div>
    </div>

    <div class="mb-3">
      <%= f.label :message, "Message", class: "form-label" %>
      <%= f.text_area :message, class: "form-control", rows: 5, required: true, placeholder: "Write your message here" %>
      <div class="invalid-feedback">
        Please enter your message.
      </div>
    </div>

    <%= f.submit "Send Message", class: "btn btn-primary" %>
  <% end %>
</div>

<script>
  // Example Bootstrap 5 client-side validation
  (() => {
    'use strict'
    const forms = document.querySelectorAll('.needs-validation')
    Array.from(forms).forEach(form => {
      form.addEventListener('submit', event => {
        if (!form.checkValidity()) {
          event.preventDefault()
          event.stopPropagation()
        }
        form.classList.add('was-validated')
      }, false)
    })
  })()
</script>

app/views/pages/home.html.erb
<% if user_signed_in? %>
  <table class="table mt-4">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Jacob</td>
      <td>Thornton</td>
      <td>@fat</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>John</td>
      <td>Doe</td>
      <td>@social</td>
    </tr>
  </tbody>
</table>
<% else %>
  <h1>Home Page</h1>
<% end %>

app/views/questions/index.html.erb
<%= turbo_frame_tag 'main_dashboard' do %>
  <div class="d-flex align-items-center justify-content-between mb-4">
<h1>New Question For <%= @entry.name %></h1>
    <%= link_to "Cancel", entry_path(@entry), class: "btn btn-sm btn-outline-danger" %>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <%= form_with(model: [@entry, @question], local: false) do |form| %>
            <div class="form-floating mb-4">
              <%= form.text_field :text, placeholder: 'Quiz Question', class: 'form-control form-control-lg', autofocus: true %>
              <%= form.label :text, "Quiz Question" %>
              <% if @question.errors[:text].any? %>
                <div class="text-danger mt-1"><%= @question.errors[:text].first %></div>
              <% end %>
            </div>

           <% @question.answers.each do |answer| %>
            <div class="form-floating mb-4">
              <%= form.fields_for :answers, answer do |ff| %>
                <%= ff.text_field :answer_text, placeholder: 'Quiz Answer', class: 'form-control form-control-lg', autofocus: true %>
                <%= ff.label :answer_text, "Quiz Answer" %>
              <% end %>
            </div>
          <% end %>


            <%= form.submit "+ Create New Quiz Question", class: "btn btn-primary" %> 
            <%= form.submit "Add answer", class: "btn btn-info" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/questions/show.html.erb
# <h1><%= @entry.title || "Entry Details" %></h1>

# <h2>Questions for this Entry</h2>

# <% if @entry.questions.any? %>
#   <ul class="list-group">
#     <% @entry.questions.each do |question| %>
#       <li class="list-group-item">
#         <%= link_to question.text, entry_question_path(@entry, question) %>
#       </li>
#     <% end %>
#   </ul>
# <% else %>
#   <p class="text-muted">No questions found for this entry.</p>
# <% end %>

# <div class="mt-3">
#   <%= link_to "Add New Question", new_entry_question_path(@entry), class: "btn btn-primary" %>
# </div>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
<div class="toast align-items-center text-bg-<%= flash_class(type) %> border-0 position-absolute top-0 end-0 z-1 mt-5 me-5" role="alert" aria-live="assertive" aria-atomic="true" data-controller="toast">
  <div class="d-flex">
    <div class="toast-body">
      <%= message %>
    </div>
    <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
  </div>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-white border-bottom mb-5">
  <div class="container">
   <%= logo('h4') %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Left-aligned links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to('About', about_path, class: 'nav-link') %>
        </li>
      </ul>
      <!-- Right-aligned links -->
      <ul class="navbar-nav mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
              data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-person-circle"></i>
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
              <li>
                <h6 class="dropdown-header">
                  Signed in as: <br> <%= current_user.email %>
                </h6>
              </li>
              <li><hr class="dropdown-divider"></li>
                <%= link_to('Statistics', stats_path, class: 'dropdown-item') %>
              <li>
                <%= link_to('Add Quiz', new_entry_path, class: 'dropdown-item') %>
              </li>
              <li>
                <%= link_to('Account', edit_user_registration_path, class: 'dropdown-item') %>
              </li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <%= link_to 'Sign out', destroy_user_session_path,
                    data: { turbo_method: :delete }, class: 'dropdown-item' %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>